### ISSUE TITLE
JBD Serial Connection - No SoC read out of BMS and duplicate VRM ID

### ISSUE THREAD

**Issue by dersch81** [Louisvdw/dbus-serialbattery#981] opened 2024-02-23 23:09 UTC
### Describe the bug

All Versions (instead of v1.0.20230531) create duplicate VRM Id's with JBD BMS with serial connection. Also after restarting dbus-serialbattery the SOC is wrong, for example it had counted 77% and after restart it shows 97%.  Due to = SoC: None%

The duplicate VRM Id is due to the new Serial Number field. I have 3 BMS. One has a unique serial and the two other get the same. I don't know from where it get the serial but i cant control this. It is not match the serial field i can set in the bms setting. 

### How to reproduce

Install any version later than v1.0.20230531 with USB connected JBD BMS

### Expected behavior

Take the serial out of the BMS serial setting in the right way and read the SoC value of the BMS

### Driver version

v1.1.20240121

### Venus OS device type

Raspberry Pi 4

### Venus OS version

v3.21

### BMS type

Smart BMS (LLT, JBD, Overkill Solar)

### Cell count

16

### Battery count

3

### Connection type

Serial USB adapter to TTL

### Config file

```ini
[DEFAULT]

; If you want to add custom values/settings, then check the values/settings you want to change in "config.default.ini"
; and insert them below to persist future driver updates.

; Example (remove the semicolon ";" to uncomment and activate the value/setting):
MAX_BATTERY_CHARGE_CURRENT = 85.0
MAX_BATTERY_DISCHARGE_CURRENT = 95.0
CCCM_CV_ENABLE = False
DCCM_CV_ENABLE = False
CCCM_T_ENABLE = False
DCCM_T_ENABLE = False
CCCM_SOC_ENABLE = False

MAX_CELL_VOLTAGE = 3.463

CUSTOM_BATTERY_NAMES = /dev/ttyACM0:Das Pack Drei,/dev/ttyACM1:Das Pack Zwei,/dev/ttyACM2:Das Pack Eins
```

### Relevant log output

```shell
@4000000065d91b59340bb524 INFO:SerialBattery:Testing Jkbms
@4000000065d91b5a08bfa59c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91b5a0949b174 INFO:SerialBattery:Testing Lifepower
@4000000065d91b5a197789f4 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91b5a19d03144 INFO:SerialBattery:Testing LltJbd
@4000000065d91b5a33364484 INFO:SerialBattery:Connection established to LltJbd
@4000000065d91b5a333b3a0c INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyACM1
@4000000065d91b5a333f7414 INFO:SerialBattery:========== Settings ==========
@4000000065d91b5a33449494 INFO:SerialBattery:> Connection voltage: 52.73V | Current: -19.93A | SoC: None%
@4000000065d91b5a3348da54 INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
@4000000065d91b5a334d27e4 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@4000000065d91b5a3351a83c INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 85.0A | MAX BATTERY DISCHARGE CURRENT: 95.0A
@4000000065d91b5a3355f9b4 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0A | MAX BATTERY DISCHARGE CURRENT: 300.0A (read from BMS)
@4000000065d91b5a335a00f4 INFO:SerialBattery:> CVCM:     True
@4000000065d91b5a335ea08c INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.463V
@4000000065d91b5a336301a4 INFO:SerialBattery:> CCCM CV:  False | DCCM CV:  False
@4000000065d91b5a33672824 INFO:SerialBattery:> CCCM T:   False | DCCM T:   False
@4000000065d91b5a336ba0ac INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: True
@4000000065d91b5a3371077c INFO:SerialBattery:Serial Number/Unique Identifier: 21_302.0Ah
@4000000065d91b5b15cd8524 INFO:SerialBattery:Found existing battery with DeviceInstance = 1
@4000000065d91b5b25143dac INFO:SerialBattery:DeviceInstance = 1
@4000000065d91b5b251c733c INFO:SerialBattery:Used device instances: ['1', '2']
@4000000065d91b5b25237434 INFO:SerialBattery:com.victronenergy.battery.ttyACM1
@4000000065d91b5b348ca4f4 INFO:SerialBattery:publish config values = True
@4000000065d91ca408191114 INFO:SerialBattery:
@4000000065d91ca4081cca34 INFO:SerialBattery:Starting dbus-serialbattery
@4000000065d91ca4082d8374 INFO:SerialBattery:Venus OS v3.21
@4000000065d91ca408323a7c INFO:SerialBattery:dbus-serialbattery v1.2.20240219beta
@4000000065d91cb4092f66fc INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
@4000000065d91cb40935fa94 INFO:SerialBattery:Testing Daly at address "\x40"
@4000000065d91cb4111ad66c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91cb4112117fc INFO:SerialBattery:Testing Daly at address "\x80"
@4000000065d91cb418c7393c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91cb418cbd104 INFO:SerialBattery:Testing Ecs
@4000000065d91cb41c5cd37c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91cb41c62e244 INFO:SerialBattery:Testing HeltecModbus
@4000000065d91cb80ae13994 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91cb80ae7c944 INFO:SerialBattery:Testing HLPdataBMS4S
@4000000065d91cb83b372c0c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91cb83b3b17f4 INFO:SerialBattery:Testing Jkbms
@4000000065d91cb90fb026c4 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91cb910060724 INFO:SerialBattery:Testing Lifepower
@4000000065d91cb920fbf264 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91cb92154092c INFO:SerialBattery:Testing LltJbd
@4000000065d91cb93b5260e4 INFO:SerialBattery:Connection established to LltJbd
@4000000065d91cb93b5769f4 INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyACM1
@4000000065d91cb93b5cc50c INFO:SerialBattery:========== Settings ==========
@4000000065d91cb93b67060c INFO:SerialBattery:> Connection voltage: 53.38V | Current: 20.63A | SoC: None%
@4000000065d91cb93b6d479c INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
@4000000065d91cb93b73ead4 INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@4000000065d91cb93b7eb0a4 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 85.0A | MAX BATTERY DISCHARGE CURRENT: 95.0A
@4000000065d91cb93b844e24 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0A | MAX BATTERY DISCHARGE CURRENT: 300.0A (read from BMS)
@4000000065d91cb93b89cc64 INFO:SerialBattery:> CVCM:     True
@4000000065d91cb93b9038ec INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.463V
@4000000065d91cb93b9699bc INFO:SerialBattery:> CCCM CV:  False | DCCM CV:  False
@4000000065d91cba00013a74 INFO:SerialBattery:> CCCM T:   False | DCCM T:   False
@4000000065d91cba00059b8c INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: True
@4000000065d91cba000acbac INFO:SerialBattery:Serial Number/Unique Identifier: 21_302.0Ah
@4000000065d91cbb02bf0e6c INFO:SerialBattery:Found existing battery with DeviceInstance = 1
@4000000065d91cbb120194bc INFO:SerialBattery:DeviceInstance = 1
@4000000065d91cbb1206ebec INFO:SerialBattery:Used device instances: ['1', '2']
@4000000065d91cbb120c71fc INFO:SerialBattery:com.victronenergy.battery.ttyACM1
@4000000065d91cbb2209285c INFO:SerialBattery:publish config values = True
@4000000065d91eed1fe7cb14 INFO:SerialBattery:
@4000000065d91eed1fed456c INFO:SerialBattery:Starting dbus-serialbattery
@4000000065d91eed1ffb187c INFO:SerialBattery:dbus-serialbattery v1.1.20240121
@4000000065d91efd20b3d574 INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
@4000000065d91efd20bde3ac INFO:SerialBattery:Testing Daly at address "\x40"
@4000000065d91efd28a382d4 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91efd28acba34 INFO:SerialBattery:Testing Daly at address "\x80"
@4000000065d91efd305bebc4 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91efd306171d4 INFO:SerialBattery:Testing Ecs
@4000000065d91efd33e3d61c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91efd33e9e4e4 INFO:SerialBattery:Testing HeltecModbus
@4000000065d91f0124569eb4 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91f01245dc2d4 INFO:SerialBattery:Testing HLPdataBMS4S
@4000000065d91f0219178bbc ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91f02191c852c INFO:SerialBattery:Testing Jkbms
@4000000065d91f022962e6ec ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91f0229af16d4 INFO:SerialBattery:Testing Lifepower
@4000000065d91f0239cc4d84 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d91f023a1f8634 INFO:SerialBattery:Testing LltJbd
@4000000065d91f0318b3343c INFO:SerialBattery:Connection established to LltJbd
@4000000065d91f0318b92f7c INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyACM1
@4000000065d91f0318be9e1c INFO:SerialBattery:========== Settings ==========
@4000000065d91f0318c502d4 INFO:SerialBattery:> Connection voltage: 53.94V | Current: 47.12A | SoC: None%
@4000000065d91f0318ca2f0c INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
@4000000065d91f0318cf7e6c INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@4000000065d91f0318d53744 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 85.0A | MAX BATTERY DISCHARGE CURRENT: 95.0A
@4000000065d91f0318da9e14 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0A | MAX BATTERY DISCHARGE CURRENT: 300.0A (read from BMS)
@4000000065d91f0318dfab0c INFO:SerialBattery:> CVCM:     True
@4000000065d91f0318eddbdc INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.463V
@4000000065d91f0318f5176c INFO:SerialBattery:> CCCM CV:  False | DCCM CV:  False
@4000000065d91f0318fb87dc INFO:SerialBattery:> CCCM T:   False | DCCM T:   False
@4000000065d91f0319018ed4 INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: True
@4000000065d91f0319095aec INFO:SerialBattery:Serial Number/Unique Identifier: 21_302.0Ah
@4000000065d91f0418126c14 INFO:SerialBattery:Found existing battery with DeviceInstance = 1
@4000000065d91f04287f0ecc INFO:SerialBattery:DeviceInstance = 1
@4000000065d91f0428874844 INFO:SerialBattery:Used device instances: ['1', '2']
@4000000065d91f04288e06d4 INFO:SerialBattery:com.victronenergy.battery.ttyACM1
@4000000065d91f04386f9fcc INFO:SerialBattery:publish config values = True
@4000000065d91ff12cec251c INFO:SerialBattery:
@4000000065d91ff12cf197a4 INFO:SerialBattery:Starting dbus-serialbattery
@4000000065d91ff12d05c3b4 INFO:SerialBattery:Venus OS v3.21
@4000000065d91ff12d0b269c INFO:SerialBattery:dbus-serialbattery v1.2.20240223dev
@4000000065d920012dcd78b4 INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
@4000000065d920012dd106dc INFO:SerialBattery:Testing Daly at address "\x40"
@4000000065d9200135acce7c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9200135b4a64c INFO:SerialBattery:Testing Daly at address "\x80"
@4000000065d9200201c4c81c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9200201caa804 INFO:SerialBattery:Testing Ecs
@4000000065d92002056bfe2c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d920020573418c INFO:SerialBattery:Testing HeltecModbus
@4000000065d920052fdd613c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d920052fe1be6c INFO:SerialBattery:Testing HLPdataBMS4S
@4000000065d92006248d6a0c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d920062494e034 INFO:SerialBattery:Testing Jkbms
@4000000065d9200634ce361c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d92006356188f4 INFO:SerialBattery:Testing Lifepower
@4000000065d920070abf7124 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d920070b3f0164 INFO:SerialBattery:Testing LltJbd
@4000000065d92007273bf00c INFO:SerialBattery:Connection established to LltJbd
@4000000065d920072741dbac INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyACM1
@4000000065d92007274761bc INFO:SerialBattery:========== Settings ==========
@4000000065d92007274d5cfc INFO:SerialBattery:> Connection voltage: 53.74V | Current: 34.74A | SoC: None%
@4000000065d9200727565dac INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
@4000000065d92007275ab30c INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@4000000065d92007276092f4 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.463V
@4000000065d920072765c6fc INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 85.0A | MAX BATTERY DISCHARGE CURRENT: 95.0A
@4000000065d92007276bb29c INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0A | MAX BATTERY DISCHARGE CURRENT: 300.0A (read from BMS)
@4000000065d920072770a43c INFO:SerialBattery:> CVCM:     True
@4000000065d9200727791c34 INFO:SerialBattery:> CCCM CV:  False | DCCM CV:  False
@4000000065d92007277ea62c INFO:SerialBattery:> CCCM T:   False | DCCM T:   False
@4000000065d920072783ca94 INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: True
@4000000065d92007278a2f4c INFO:SerialBattery:Serial Number/Unique Identifier: 21_302.0Ah
@4000000065d920082a4c25dc INFO:SerialBattery:Found existing battery with DeviceInstance = 1
@4000000065d920083504ea04 INFO:SerialBattery:DeviceInstance = 1
@4000000065d92008350beee4 INFO:SerialBattery:Used DeviceInstances = ['1', '2']
@4000000065d920083511d2b4 INFO:SerialBattery:com.victronenergy.battery.ttyACM1
@4000000065d9200908ad0be4 INFO:SerialBattery:publish config values = True
@4000000065d9208802e4ab54 INFO:SerialBattery:
@4000000065d9208802e9431c INFO:SerialBattery:Starting dbus-serialbattery
@4000000065d9208803070834 INFO:SerialBattery:dbus-serialbattery v1.0.20240102beta
@4000000065d92098037cefcc INFO:SerialBattery:-- Testing BMS: 1 of 3 rounds
@4000000065d920980383680c INFO:SerialBattery:Testing Daly at address "\x40"
@4000000065d920980b85a36c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d920980b8cdb14 INFO:SerialBattery:Testing Daly at address "\x80"
@4000000065d9209813de4fb4 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9209813de633c INFO:SerialBattery:Testing Ecs
@4000000065d92098186ae484 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d92098186afbf4 INFO:SerialBattery:Testing HeltecModbus
@4000000065d9209c082837fc ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9209c082d681c INFO:SerialBattery:Testing HLPdataBMS4S
@4000000065d9209c38938734 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9209c389a035c INFO:SerialBattery:Testing Jkbms
@4000000065d9209d0e4c8f84 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9209d0ec286bc INFO:SerialBattery:Testing Lifepower
@4000000065d9209d1ff7ff84 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9209d205dbe64 INFO:SerialBattery:Testing LltJbd
@4000000065d9209d3a1c2ad4 INFO:SerialBattery:Connection established to LltJbd
@4000000065d9209d3a28fffc INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyACM1
@4000000065d9209d3a503324 INFO:SerialBattery:========== Settings ==========
@4000000065d9209d3a5a974c INFO:SerialBattery:> Connection voltage: 53.83V | Current: 33.17A | SoC: None%
@4000000065d9209d3a657c5c INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
@4000000065d9209d3a6dc95c INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@4000000065d9209d3a81b6ec INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 85.0A | MAX BATTERY DISCHARGE CURRENT: 95.0A
@4000000065d9209d3a9327c4 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0A | MAX BATTERY DISCHARGE CURRENT: 300.0A (read from BMS)
@4000000065d9209d3a9ec46c INFO:SerialBattery:> CVCM:     True
@4000000065d9209d3aaa9bac INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.463V
@4000000065d9209d3b4bae0c INFO:SerialBattery:> CCCM CV:  False | DCCM CV:  False
@4000000065d9209d3b54dd9c INFO:SerialBattery:> CCCM T:   False | DCCM T:   False
@4000000065d9209d3b5ab99c INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: True
@4000000065d9209d3b61a324 INFO:SerialBattery:Serial Number/Unique Identifier: 21_302.0Ah
@4000000065d9209f02bb8044 INFO:SerialBattery:Found existing battery with DeviceInstance = 1
@4000000065d9209f1a0de23c INFO:SerialBattery:DeviceInstance = 1
@4000000065d9209f1a1446f4 INFO:SerialBattery:Used device instances: ['1', '2']
@4000000065d9209f1a213774 INFO:SerialBattery:com.victronenergy.battery.ttyACM1
@4000000065d9209f2954b61c INFO:SerialBattery:publish config values = True
@4000000065d92105175de53c INFO:SerialBattery:Starting dbus-serialbattery
@4000000065d9210517697244 INFO:SerialBattery:dbus-serialbattery v1.0.20230531
@4000000065d92105176ed914 INFO:SerialBattery:Testing Daly
@4000000065d921051f50e62c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d921051f5ac96c INFO:SerialBattery:Testing Daly
@4000000065d921052757ec1c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d92105275de374 INFO:SerialBattery:Testing Ecs
@4000000065d921052b0caeec ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d921052b12449c INFO:SerialBattery:Testing HeltecModbus
@4000000065d921091a5c776c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d921091a5c8af4 INFO:SerialBattery:Testing HLPdataBMS4S
@4000000065d9210d38f23d4c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9210d3915ab9c INFO:SerialBattery:Testing Jkbms
@4000000065d9210e0e6d4e54 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9210e0ee1da44 INFO:SerialBattery:Testing Lifepower
@4000000065d9210e208c542c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9210e20ee698c INFO:SerialBattery:Testing LltJbd
@4000000065d9210e36b0b5a4 INFO:SerialBattery:Connection established to LltJbd
@4000000065d9210e36b7f51c INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyACM1
@4000000065d9210e36bcbbc4 INFO:SerialBattery:========== Settings ==========
@4000000065d9210e36c2f96c INFO:SerialBattery:> Connection voltage: 53.99V | Current: 41.98A | SoC: 77.22%
@4000000065d9210e36c85484 INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
@4000000065d9210e36cf651c INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@4000000065d9210e36d548ec INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 85.0A | MAX BATTERY DISCHARGE CURRENT: 95.0A
@4000000065d9210e36dbffac INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0A | MAX BATTERY DISCHARGE CURRENT: 300.0A (read from BMS)
@4000000065d9210e36e25c94 INFO:SerialBattery:> CVCM:     True
@4000000065d9210e36e9b764 INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.463V
@4000000065d9210e36f14ccc INFO:SerialBattery:> CCCM CV:  False | DCCM CV:  False
@4000000065d9210e36f7a1e4 INFO:SerialBattery:> CCCM T:   False | DCCM T:   False
@4000000065d9210e370912bc INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: True
@4000000065d9210f090aa4d4 INFO:SerialBattery:DeviceInstance = 4
@4000000065d9210f090abc44 INFO:SerialBattery:com.victronenergy.battery.ttyACM1
@4000000065d9210f168caabc INFO:SerialBattery:publish config values = 1
@4000000065d9210f1b0d29cc INFO:SerialBattery:DeviceInstance = 4
@4000000065d9210f1b18bea4 INFO:SerialBattery:Changed DeviceInstance = 4
@4000000065d92187279f8054 INFO:SerialBattery:Starting dbus-serialbattery
@4000000065d9218727ae320c INFO:SerialBattery:dbus-serialbattery v1.0.20230531
@4000000065d9218727b6a234 INFO:SerialBattery:Testing Daly
@4000000065d921872f9ec9cc ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d921872fa63ff4 INFO:SerialBattery:Testing Daly
@4000000065d9218737668884 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d92187376c3d74 INFO:SerialBattery:Testing Ecs
@4000000065d921873b1553fc ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d921873b1b89d4 INFO:SerialBattery:Testing HeltecModbus
@4000000065d9218b2a859114 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d9218b2a8b0784 INFO:SerialBattery:Testing HLPdataBMS4S
@4000000065d921900e0d38ac ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d921900e19851c INFO:SerialBattery:Testing Jkbms
@4000000065d921901f52361c ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d921901fa38e54 INFO:SerialBattery:Testing Lifepower
@4000000065d9219030122124 ERROR:SerialBattery:>>> ERROR: No reply - returning
@4000000065d921903085322c INFO:SerialBattery:Testing LltJbd
@4000000065d921910a750a44 INFO:SerialBattery:Connection established to LltJbd
@4000000065d921910a8440cc INFO:SerialBattery:Battery LLT/JBD connected to dbus from /dev/ttyACM1
@4000000065d921910a84583c INFO:SerialBattery:========== Settings ==========
@4000000065d921910a872314 INFO:SerialBattery:> Connection voltage: 53.67V | Current: 24.46A | SoC: 77.29%
@4000000065d921910a95bd5c INFO:SerialBattery:> Cell count: 16 | Cells populated: 16
@4000000065d921910a96b75c INFO:SerialBattery:> LINEAR LIMITATION ENABLE: True
@4000000065d921910afca51c INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 85.0A | MAX BATTERY DISCHARGE CURRENT: 95.0A
@4000000065d921910afcc074 INFO:SerialBattery:> MAX BATTERY CHARGE CURRENT: 300.0A | MAX BATTERY DISCHARGE CURRENT: 300.0A (read from BMS)
@4000000065d921910b01a65c INFO:SerialBattery:> CVCM:     True
@4000000065d921910b1107dc INFO:SerialBattery:> MIN CELL VOLTAGE: 2.9V | MAX CELL VOLTAGE: 3.463V
@4000000065d921910b111f4c INFO:SerialBattery:> CCCM CV:  False | DCCM CV:  False
@4000000065d921910b14b544 INFO:SerialBattery:> CCCM T:   False | DCCM T:   False
@4000000065d921910b1b0e44 INFO:SerialBattery:> CCCM SOC: False | DCCM SOC: True
@4000000065d9219113581c3c INFO:SerialBattery:DeviceInstance = 4
@4000000065d92191136ba054 INFO:SerialBattery:com.victronenergy.battery.ttyACM1
@4000000065d921911f416954 INFO:SerialBattery:publish config values = 1
```

**Comment by mr-manuel** [comment] 2024-02-23 23:17
Please install todays version, there the issue is fixed.

**Comment by mr-manuel** [comment] 2024-02-24 18:25
Since the JBD does not seem to provide a serial number that we can read, we have to create a unique identifier. In this case it contains also the capacity. Change the capacity of one battery by increasing or decreasing 1 Ah. The SoC is only None when starting. I'm working on this issue, but it is not that urgent.

**Comment by dersch81** [comment] 2024-02-24 19:55
It would be good to have that Unique ID configurable in the config.ini

Also the Soc is always none. I had it running for a couple of hrs and it did not change.

**Comment by mr-manuel** [comment] 2024-02-24 21:32
> It would be good to have that Unique ID configurable in the config.ini

That would make no sense. The unique identifier is needed to identify a BMS indipendent of where and how it is attached. Therefore the value has to be fetched from the BMS.

> Also the Soc is always none. I had it running for a couple of hrs and it did not change.

Please share a screenshot and dbus-spy of the battery where we can see the SoC value.

**Comment by mr-manuel** [comment] 2024-02-25 10:00
The problem with the None SoC at driver startup is solved in the next release.

**Comment by mr-manuel** [comment] 2024-02-27 13:55
The problem was fixed with `v1.2.20240227dev`.

**Closed by mr-manuel** 2024-02-27 13:55 UTC
Labels: bug

**Comment by gustogyver** [comment] 2024-02-28 00:29
Where can I find the version  v1.2.20240227dev? Is there a download link somewhere or only over the install script?

**Comment by mr-manuel** [comment] 2024-02-28 05:37
https://github.com/mr-manuel/venus-os_dbus-serialbattery/releases
