### ISSUE TITLE
VRM instance changes sporadically

### ISSUE THREAD

**Issue by Micha854** [Louisvdw/dbus-serialbattery#738] opened 2023-07-02 09:46 UTC
### Describe the bug

Hello,

I have two installations with the Serial Driver and with both I observe the following:

If you start the Raspberry again, the VRM Instance sometimes changes.

This is bad because my graphs then remain empty in the expanded view...

Would it be possible to tell the driver (config.ini) VRM Instance = 1? That would solve the problem

Even if the PI is freshly installed, this problem occurs...

in both installations the battery is connected to an RS485 adapter

### How to reproduce

when restarting the Pi, sporadically

### Expected behavior

..

### Driver version

newest dev

### Venus OS device type

Raspberry Pi

### Venus OS version

3.00

### BMS type

Daly Smart BMS

### Cell count

15

### Connection type

Serial USB adapter to RS485

### Config file

```ini
..
```

### Relevant log output

```shell
..
```

**Comment by transistorgit** [comment] 2023-07-02 10:25
Probably duplicate of #718

**Comment by mr-manuel** [comment] 2023-07-02 14:38
@Micha854 if you use the search you will find a lot of issues and discussions about that.

**Closed by mr-manuel** 2023-07-02 14:38 UTC
Labels: duplicate
