### ISSUE TITLE
Wrong cell voltage reading Daly BMS

### ISSUE THREAD

**Issue by ats-rozruch** [Louisvdw/dbus-serialbattery#397] opened 2023-01-07 21:56 UTC
**Describe the bug**
I have 12S Daly BMS and function read_cells_volts always returning from here

if cells_volts_data is False:
logger.warning("read_cells_volts")
return False

I had to change
cellvolt_buffer = b"\xA5\x40\x94\x08\x00\x00\x00\x00\x00\x00\x00\x00\x82\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
to
cellvolt_buffer = b"\xA5\x40\x94\x08\x00\x00\x00\x00\x00\x00\x00\x00\x82"

becuse BMS doesn't want to answer to that so huge command

Second thing because cell_count is 12  maxFrame were counted wrong 

            if (int(self.cell_count) % 3) == 0:
                maxFrame = (int(self.cell_count / 3))
            else:
                maxFrame = (int(self.cell_count / 3) + 1)

Third thing lenFixed should be 13 not 12 because each returned frame with cell voltage have own CRC  
            lenFixed = (maxFrame * 13) # 0xA5, 0x01, 0x95, 0x08 + 1 byte frame + 6 byte data + 1byte reserved

**Comment by towatai** [comment] 2023-02-05 14:28
Thanks, the "cellvolt_buffer" fixed the problem for me with no cell voltages being read out on my Daly 24V, 8S via RS485. Via UART it worked without problems.

**Comment by transistorgit** [comment] 2023-03-06 20:59
Thanks, I had the same problem. I have 2 Dalys, one by RS485 and one by UART. The RS485 one was not working. 

- The old size of cellvolt_buffer was meaningless, as it is a buffer for the command, that is 13 bytes always. 
- The maxframe count was no problem for me as I have 16s, but I confirm that your fix is right
- lenFixed was also a bug, confirmed

With all these fixes, my daly with RS485 is working fine now. I use it together with [AggregateBatteries](https://github.com/Dr-Gigavolt/dbus-aggregate-batteries) and that would not work without the cell voltages.

As an explanation why the big buffer is a problem for RS485 but not for UART, I think serialbattery still sends the buffer bytes when Daly already starts to reply. With UART this is ok, because its bidirectional. But RS485 is half-duplex so the datastreams collide and the reply is unreadable.

Further, there is still another problem. After reading cell voltages, the next operation is read_soc_data and the first try always fails. So this leads to a log file flooded with warnings "ERROR:SerialBattery:>>> ERROR: No reply - returning".
This happens with both interface types. 
I tried a quick fix with sleep(0.5) between calls but no success. As the read function always flushes the buffers, I don't know where the influencing is. The commands on the serial port for read_soc_data are always the same (a540900800000000000000007d), but on the first try after read_cells_volts the Dalys just don't answer anything. 
Can somebody confirm this behavior? @towatai @ats-rozruch ?

**Comment by transistorgit** [comment] 2023-03-07 20:43
@ats-rozruch do you plan to make a pull request? if not i would do

**Comment by transistorgit** [comment] 2023-03-08 00:46
seems that I was able to also fix the "No reply- Returning" bug, and improved some other bugs. I will create a pull request together with your suggestions if you don't mind.

**Comment by mr-manuel** [comment] 2023-04-20 13:59
@transistorgit  is this issue fixed with your PR or is still something open?

**Comment by transistorgit** [comment] 2023-04-20 14:54
yes, I think it's fixed. Can only test with 2 16s systems, though. Runs fine for a month now.

**Closed** 2023-04-20 15:29 UTC
