### ISSUE TITLE
Daly bms sleep mode causing incorrect data in MP2 gx webinterface

### ISSUE THREAD

**Issue by LukasBenner** [Louisvdw/dbus-serialbattery#193] opened 2022-09-05 19:29 UTC
**Describe the bug**
The battery is fully loaded and the daly bms stops charging.
Shortly after it goes into sleep mode and doesn't respond on the uart interface.
In the WebInterface of the MP2 GX and on the VRM Portal wrong values are shown.
e.g the current is displayed with 20 amps but is 0 in real.

The driver log ("/var/log/dbus-serialbattery.ttyUSB0/current") shows "No reply - returning"

![image](https://user-images.githubusercontent.com/36197800/188504831-659d7a75-5a73-42b6-be70-4145ce15752a.png)

**To Reproduce**
1. Stop charging so the daly bms goes into sleep mode.
2. Open the log from above.

**Expected behavior**
I'd expect the web interface of the MP2 GX to show the correct data.
I'd expect the software to differentiate between the daly bms being in sleep mode 
and the daly bms not responding.

**VenusOS (please complete the following information):**
 - Device type MP2 GX
 - Firmware Version v2.90

**Battery/BMS (please complete the following information):**
 - BMS/Battery type: Daly
 - Cells: 16
 - Interface: USB-RS232 UART

**Additional context**

**Comment by LukasBenner** [comment] 2022-11-12 11:36
The same behavior can be observed when completely disconnecting the BMS.
This is kind of a critical bug because the soc regulates the parameters for charging and discharging.
Although the Daly BMS will cut the battery when fully charged or discharged, the allowed current for charging and discharging is not updated.

I just connected the BMS to a cerbogx of a friend of mine to test the software. I'd expect my installation to stop charging while the BMS is not connected. Unfortunately it just keeps charging. Went from 61% to 69% percent without any error or something.

**Comment by mr-manuel** [comment] 2023-05-01 17:43
@transistorgit maybe you know, if this is still an issue?

**Comment by transistorgit** [comment] 2023-05-01 18:24
Yes, I think so. There is no means of state handling employed. If the bms stops answering, the last values will be there forever. 
It should be easy to solve with a timeout in refresh_data. If there isn't any new data for 1 minute, set AllowToCharge/Discharge to false. 

How is it done in other bms? Wonder if it shouldn't be a base class function?

**Comment by mr-manuel** [comment] 2023-05-02 06:52
Theoretically there should already be a check, but it seems that it's not working.

https://github.com/Louisvdw/dbus-serialbattery/blob/fce00b998a929fcf7d0b75b2f4b11de4823d366a/etc/dbus-serialbattery/dbushelper.py#L322-L350

**Comment by transistorgit** [comment] 2023-05-03 20:24
just did a real test with my dalys with branch jkbms_ble.
In both cases, unplugging USB or unplugging the serial connector at the BMS, the remote console shows correctly "Not connected" after a minute.
Until 1 minute is over the values stay frozen, that can be optimized.

**Comment by transistorgit** [comment] 2023-05-03 20:30
created pull request https://github.com/mr-manuel/venus-os_dbus-serialbattery/pull/3 
is that right? or should it go into luisvdw's repo?

**Comment by mr-manuel** [comment] 2023-05-04 05:07
It doesn‘t matter in which repo :-) it will get merged in both ways. I test it today with a JKBMS.

**Comment by mr-manuel** [comment] 2023-05-04 09:09
@transistorgit I did some testing and I have this behaviour: After 10 seconds the BMS is shown as `Not connected` and all values are `--`. In this case the charging/discharging is not blocked, since there is no BMS connected. This can be good or bad depending on the cause.

Would it make more sense to keep the driver "connected", but blocking charge/discharge and eventually let the user select/change the behaviour by config file? In this case the driver/system has to be restarted, if a BMS is removed from the device.

What are your thoughts?

**Comment by transistorgit** [comment] 2023-05-04 13:55
yes, I had quite some error handling to do until I had fixed all Type errors. just very probable that I misses one that is now triggered with your BMS. Can you send me the log line with the line no where is crashed?

If all exceptions are handled, the behaviour should be like I wrote. And I had also no problem with redetecting the device then. This is in my view the cleanest solution.

**Comment by mr-manuel** [comment] 2023-05-04 13:56
Ok, in my case somehow `ttyUSB0` gets blocked from the driver. When I disconnect from the USB port `ttyUSB0` and connect it again, before the driver exited, then the devices is recognized as `ttyUSB1`. If I reconnect it again after the driver exited, then it's recognized as `ttyUSB0` again.

I made some more changes in the `jkbms_ble` branch in my fork, that are merged later today with Louisvdw `jkbms_ble` branch:
* Added: Alert is triggered, when BMS communication is lost
* Added: Block charge/discharge when BMS communication is lost. Can be enabled trough the config file

**Comment by mr-manuel** [comment] 2023-05-04 13:58
We wrote nearly at the same time :P I already fixed the other errors, so none left. If the adapter does not change port, all is working as expected. In my eyes we can close this now. What do you think?

**Closed** 2023-05-04 14:26 UTC
Labels: bug
