### ISSUE TITLE
Device new name does not survive reboot

### ISSUE THREAD

**Issue by seamaster101** [Louisvdw/dbus-serialbattery#612] opened 2023-05-06 03:16 UTC
### Describe the bug

I have two JKBMSs connected and try to rename then Battery1 and Battery2 respectively

The names are excepted and presented properly till the unit is rebooted. 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/7897023/236595403-1f04cae7-992d-410a-8580-20fb69f87c37.png">

Once the unit is rebooted it goes back to default SerialBattery(Jkbms) name
 
<img width="632" alt="image" src="https://user-images.githubusercontent.com/7897023/236595188-a755e947-a3e4-489a-a7bd-3f43515b6ca8.png">

### How to reproduce

rename SerialBattery
reboot device

### Expected behavior

Needs to keep the new devices name after the reboot

### Driver version

0.14.3

### Venus OS device type

Please select

### Venus OS version

V3.0

### BMS type

JKBMS / Heltec BMS

### Cell count

4

### Connection type

Serial USB adapter to RS485

### Config file

```ini
not modified
```

### Relevant log output

```shell
not sure what is needed here
```

### Any other information that may be helpful

can provide if else is needed

**Comment by pos-ei-don** [comment] 2023-05-06 05:15
Same here in this Release. As a workaround you can Set the Name within NodeRed and Mqtt.

**Comment by seamaster101** [comment] 2023-05-06 05:17
@pos-ei-don I'm glad that you managed to confirm the renaming issue. 
Unfortunately I don't use nodeRed or MQTT

**Comment by mr-manuel** [comment] 2023-05-06 07:44
Duplicate of https://github.com/Louisvdw/dbus-serialbattery/issues/100

**Closed by mr-manuel** 2023-05-06 07:44 UTC
Labels: bug, duplicate
